apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-exporter
  namespace: monitoring
  labels:
    app: celery-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-exporter
  template:
    metadata:
      labels:
        app: celery-exporter
    spec:
      containers:
      - name: celery-exporter
        image: danihodovic/celery-exporter:latest
        args:
        - --broker-url=redis://redis:6379/0
        - --broker-transport=redis
        - --broker-password=$(REDIS_PASSWORD)
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: redis-password
        ports:
        - name: metrics
          containerPort: 9808
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: celery-exporter
  namespace: monitoring
  labels:
    app: celery-exporter
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9808
    targetPort: metrics
    protocol: TCP
  selector:
    app: celery-exporter 