# ==============================================================================
# FlightIO Unified Configuration
# Single source of truth for all service configurations
# ==============================================================================

# Application Settings
app:
  name: FlightIO Crawler
  version: 2.0.0
  environment: ${ENVIRONMENT:-production}
  debug: ${DEBUG:-false}
  
# Database Configuration
database:
  host: ${DB_HOST:-postgres}
  port: ${DB_PORT:-5432}
  name: ${DB_NAME:-flight_data}
  user: ${DB_USER:-crawler}
  password: ${DB_PASSWORD:-crawler_password}
  pool_size: ${DB_POOL_SIZE:-20}
  max_overflow: ${DB_MAX_OVERFLOW:-40}
  echo: ${DB_ECHO:-false}
  
# Redis Configuration
redis:
  host: ${REDIS_HOST:-redis}
  port: ${REDIS_PORT:-6379}
  password: ${REDIS_PASSWORD:-}
  db: ${REDIS_DB:-0}
  max_connections: ${REDIS_MAX_CONNECTIONS:-50}
  
# API Configuration
api:
  host: ${API_HOST:-0.0.0.0}
  port: ${API_PORT:-8000}
  workers: ${API_WORKERS:-4}
  reload: ${API_RELOAD:-false}
  cors_origins: ${CORS_ORIGINS:-["*"]}
  rate_limit:
    enabled: ${RATE_LIMIT_ENABLED:-true}
    requests_per_minute: ${RATE_LIMIT_RPM:-60}
    
# Crawler Configuration
crawler:
  max_concurrent: ${CRAWLER_MAX_CONCURRENT:-3}
  timeout: ${CRAWLER_TIMEOUT:-30}
  retry_attempts: ${CRAWLER_RETRY_ATTEMPTS:-3}
  user_agents:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
  
# Monitoring Configuration
monitoring:
  enabled: ${MONITORING_ENABLED:-true}
  prometheus:
    enabled: ${PROMETHEUS_ENABLED:-true}
    port: ${PROMETHEUS_PORT:-9090}
  health_check:
    enabled: true
    port: ${HEALTH_CHECK_PORT:-8080}
    interval: 60
    
# Logging Configuration
logging:
  level: ${LOG_LEVEL:-INFO}
  format: ${LOG_FORMAT:-json}
  file:
    enabled: ${LOG_FILE_ENABLED:-true}
    path: ${LOG_FILE_PATH:-/app/logs/app.log}
    max_size: ${LOG_FILE_MAX_SIZE:-100MB}
    backup_count: ${LOG_FILE_BACKUP_COUNT:-5}
    
# Security Configuration
security:
  secret_key: ${SECRET_KEY:-}
  jwt_secret: ${JWT_SECRET:-}
  jwt_algorithm: ${JWT_ALGORITHM:-HS256}
  jwt_expire_minutes: ${JWT_EXPIRE_MINUTES:-30}
  
# Site-specific Configurations
sites:
  alibaba:
    base_url: "https://www.alibaba.ir"
    rate_limit: 30
    timeout: 20
  emirates:
    base_url: "https://www.emirates.com"
    rate_limit: 20
    timeout: 25
  iran_air:
    base_url: "https://www.iranair.com"
    rate_limit: 30
    timeout: 20
    
# Error Handling
error_handling:
  max_retries: 3
  retry_delay: 5
  exponential_backoff: true
  error_types:
    - network_error
    - timeout_error
    - parsing_error 